export type RootStackParamList = {
  Welcome: undefined;
  LauncherSetup: undefined;
  PrimaryLock: undefined;
  PinSetup: undefined;
  PasswordSetup: undefined;
  PatternSetup: undefined;
  BiometricSetup: undefined;
  ProtectionSaved: undefined;
  AutoLockSettings: undefined;
  RebootRestored: undefined;
  UnlockSuccess: undefined;
  Calculator: undefined;
  AuthGate: undefined;
  PrivateHome: undefined;
  AddApps: undefined;
  ProtectionMode: undefined;
  ManageApps: undefined;
  Gallery: undefined;
  SecretEntry: undefined;
  Vault: undefined;
  Settings: undefined;
  PrivacyCenter: undefined;
  AdManagerRules: undefined;
  AppRemoved: {label: string};
};
