import type {ProtectionDraft} from '../screens/app-picker/buildProtectionPolicy';

export type RootStackParamList = {
  Welcome: undefined;
  LauncherSetup: undefined;
  PrimaryLock: undefined;
  PinSetup: undefined;
  PasswordSetup: undefined;
  PatternSetup: undefined;
  BiometricSetup: undefined;
  ProtectionSaved: undefined;
  AutoLockSettings: undefined;
  RebootRestored: undefined;
  UnlockSuccess: undefined;
  Calculator: undefined;
  AuthGate: undefined;
  PrivateHome: undefined;
  AddApps: undefined;
  ProtectionMode: {draft: ProtectionDraft; onboarding: boolean};
  ManageApps: undefined;
  RemoveApp: {app: {packageName: string; label: string; mode: 'NONE' | 'LOCK' | 'HIDE' | 'LOCK_HIDE'}};
  Gallery: undefined;
  SecretEntry: undefined;
  Vault: undefined;
  Settings: undefined;
  AppearanceSettings: undefined;
  PrivacyCenter: undefined;
  AdManagerRules: undefined;
  AppRemoved: {label: string};
};
