import type {ProtectionDraft} from '../screens/app-picker/buildProtectionPolicy';
import type {FeatureFlow, ProtectionMode} from '../types/domain';

export type RootStackParamList = {
  Welcome: undefined;
  LauncherSetup: {flow?: FeatureFlow} | undefined;
  PrimaryLock: {flow?: FeatureFlow} | undefined;
  PinSetup: {flow?: FeatureFlow} | undefined;
  PasswordSetup: {flow?: FeatureFlow} | undefined;
  PatternSetup: {flow?: FeatureFlow} | undefined;
  BiometricSetup: {flow?: FeatureFlow} | undefined;
  ProtectionSaved: {flow?: FeatureFlow} | undefined;
  AutoLockSettings: undefined;
  RebootRestored: undefined;
  UnlockSuccess: undefined;
  Calculator: undefined;
  Clock: undefined;
  Calendar: undefined;
  AuthGate: undefined;
  PrivateHome: undefined;
  AddApps: {preset?: ProtectionMode; flow?: FeatureFlow} | undefined;
  ProtectionMode: {draft: ProtectionDraft; onboarding: boolean; flow?: FeatureFlow};
  ManageApps: undefined;
  RemoveApp: {app: {packageName: string; label: string; mode: 'NONE' | 'LOCK' | 'HIDE' | 'LOCK_HIDE'}};
  Gallery: undefined;
  SecretEntry: {flow?: FeatureFlow} | undefined;
  Vault: undefined;
  Settings: undefined;
  AppearanceSettings: undefined;
  PrivacyCenter: undefined;
  AdManagerRules: undefined;
  AppRemoved: {label: string};
};
